### ISSUE TITLE
What's the best place to store PRL?

### ISSUE THREAD

**Issue by VlY1995** [brunoblock/oystermesh#10]
Hi guys!!! I have PRL on Kucoin, what's the best place to withdraw and store them? Metamask is ok? And I also had some SHL, but now balance showing 0 on Kucoin, no way to restore them? 
Thank YOU in advance. 
Ahh and concerning AKOYA, isn't it too late to receive some?

**Comment by elkaddourisaid** [comment]
Same problem over here, missed a lot with AKOYA.
Is there any chance to get AKOYA.
I've stored my SHL and PRL @ MEW.

**Comment by brunoblock** [comment]
Your only reasonable option is to rage at the opacity team who stole the oyster subreddit and twitter and are the reason why you didn't get the news about the airdrop.

**Comment by elkaddourisaid** [comment]
> Your only reasonable option is to rage at the opacity team who stole the oyster subreddit and twitter and are the reason why you didn't get the news about the airdrop.

:((
