### ISSUE TITLE
It's been almost a year and still no buyback, not even the $300k you stole when exit scamming?

### ISSUE THREAD

**Issue by Squarehead11** [brunoblock/oystermesh#14]
Pearl Recovery Program (PRP) Announcement

I am buying $1,500,000 worth of Akoya and then locking them up until Jan 1 2022. 

The buys will be spread out until mainnet is launched, hence they will be bought as AKYE (ERC-20) instead of AKY (mainnet).

After mainnet launches I will transfer 100% of my AKYE to AKY and then lock them at the protocol level. I trust the security and long term energy scalability of the Oyster meshblock more than the Ethereum blockchain, hence I will lock my coins as AKY at the protocol level instead of AKYE in an Ethereum smart contract. The coin-lock will be clearly defined in open source code and easy to audit by any dev. If mainnet takes longer than expected I don’t mind doing an interim coin-lock with Ethereum.

For anyone who doesn’t believe in what I’ve built, please dump all your AKYE at market price here: https://forkdelta.app/#!/trade/0x4c218ac55d53e9de63214f7dde5b4db2a5d48ed3-ETH

I’ll buy your AKYE for market price no questions asked. As of now there aren’t any serious sell orders, you put your money where your mouth is by selling and I will put my money where my mouth is by buying.

You can watch me accumulate AKYE here: https://etherscan.io/token/0x4c218ac55d53e9de63214f7dde5b4db2a5d48ed3?a=0xf3b72CdA9E93A08bC782B715cf56Fb9CB4F37619

**Comment by mehdmehd** [comment]
I still get PRL & SHL token. How change it against AKY?
