### ISSUE TITLE
function oy_base_encody return window.btoa error 

### ISSUE THREAD

**Issue by unsobill** [brunoblock/oystermesh#3]
![image](https://user-images.githubusercontent.com/368145/52918781-d6726e80-32af-11e9-8a9b-cd9bfdf85aa5.png)

**Comment by brunoblock** [comment]
Thank you for informing me on this issue. What exactly was typed into the message box, a string "Enter By key" or something else?

'outside latin1 range' usually means some special characters were inserted that base64 didn't want to handle.

**Comment by brunoblock** [comment]
base_encode function was upgraded to handle UTF8
