### ISSUE TITLE
Oystertalk.mesh "ERROR: One block approval per 12 hours per IP address allowed"

### ISSUE THREAD

**Issue by thehugeshort** [brunoblock/oystermesh#4]
Can't seem to access the dApp, correct me if I'm wrong but will I have to wait 12 hours before I can try to join the group again?

**Comment by brunoblock** [comment]
You need to use the same wallet you used the first time, it will remain approved to post in the group. You could also wait the 12 hours and access oyster talk via a new wallet but ideally you should re-use the same one.

**Comment by thehugeshort** [comment]
> You need to use the same wallet you used the first time, it will remain approved to post in the group. You could also wait the 12 hours and access oyster talk via a new wallet but ideally you should re-use the same one.

Okay, but then once I load the wallet and try to join, it'll remain stuck at ''Please wait, checking new block for approval...''.
