### ISSUE TITLE
Oystertalk

### ISSUE THREAD

**Issue by OysterAintOpacity** [brunoblock/oystermesh#5]
I'm having difficulty posting messages to OysterTalk, once the message is broadcast, the text remains light grey as per the screenshot.
![oystertalk](https://user-images.githubusercontent.com/48281095/53876434-a37bf900-406b-11e9-8a0d-d0ffd53830fa.jpg)

**Comment by brunoblock** [comment]
It looks like you have 1 peer connected, try and wait until your node maintains 3 or more peers before broadcasting and it should work. E0 in red means no echo packets were received in return, which means no nodes that are listening to the channel directly received your broadcast.
