### ISSUE TITLE
How to OysterTalk

### ISSUE THREAD

**Issue by mehdmehd** [brunoblock/oystermesh#6]
Hello! 

I don't use to use mesh. I actually get some PRL & SHL token and I would like to continue adventure with AKYE (even if...).

So, could you create a small tuto about how to log to chat room? Thank you very much

**Comment by svick1** [comment]
1. Open oyster.org 
2. Click AKOYA tab -> Generate, download seed key, load wallet
3. Wait until 3+ peers connect 
4. Click DAPPER tab -> Type oystertalk.mesh (all lowercase), launch, join

**Comment by pynetx** [comment]
It's been more than a week I am actively watching mesh but, there aren't any peers active. 
Shouldn't at least 1 peer be active while I am on the oyster homepage?
