### ISSUE TITLE
oystertalkmesh node

### ISSUE THREAD

**Issue by mecengine** [brunoblock/oystermesh#8]
hello
I cant connect to node for oystertalk and for akayo as well. I m using last version of chrome and firefox but still no node connection cant see any conversation of the community.
Glad if you can answer.

**Comment by mecengine** [comment]
Sorry connecting to peers.

**Comment by brunoblock** [comment]
Can you send a paste-dump of the console when it doesn't work? Do you see the flags OY_CLONE_AFFIRM or OY_CLONE_PUSH in the console? Is your internet connection particularly slow?

**Comment by mecengine** [comment]
![image](https://user-images.githubusercontent.com/49160651/56652017-fbf66c80-6692-11e9-88e8-46930d48f421.png)
Keep disconnecting and struggling to find peers. How i m going to solve this issue. I do have fast speed internet and last version of chrome and firefox.

**Comment by mecengine** [comment]
![image](https://user-images.githubusercontent.com/49160651/56652113-3d871780-6693-11e9-8adc-b526db9bd6e3.png)
That screen shot is the another one.

**Comment by brunoblock** [comment]
V5 should fix connectivity issues, it is currently being worked on.
